package com.ctvit.bean;

public class Interact_baoliao_object {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.id
	 * 
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.title
	 * 
	 * @mbggenerated
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.img
	 * 
	 * @mbggenerated
	 */
	private String img;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.is_show
	 * 
	 * @mbggenerated
	 */
	private int is_show;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.type
	 * 
	 * @mbggenerated
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.ctime
	 * 
	 * @mbggenerated
	 */
	private Integer ctime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.uid
	 * 
	 * @mbggenerated
	 */
	private String uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.jf_id
	 * 
	 * @mbggenerated
	 */
	private String jf_id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao_object.b_desc
	 * 
	 * @mbggenerated
	 */
	private String b_desc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.id
	 * 
	 * @return the value of interact_baoliao_object.id
	 * 
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao_object.id
	 * 
	 * @param id
	 *            the value for interact_baoliao_object.id
	 * 
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.title
	 * 
	 * @return the value of interact_baoliao_object.title
	 * 
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao_object.title
	 * 
	 * @param title
	 *            the value for interact_baoliao_object.title
	 * 
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.img
	 * 
	 * @return the value of interact_baoliao_object.img
	 * 
	 * @mbggenerated
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao_object.img
	 * 
	 * @param img
	 *            the value for interact_baoliao_object.img
	 * 
	 * @mbggenerated
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.is_show
	 * 
	 * @return the value of interact_baoliao_object.is_show
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.type
	 * 
	 * @return the value of interact_baoliao_object.type
	 * 
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao_object.type
	 * 
	 * @param type
	 *            the value for interact_baoliao_object.type
	 * 
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.ctime
	 * 
	 * @return the value of interact_baoliao_object.ctime
	 * 
	 * @mbggenerated
	 */
	public Integer getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao_object.ctime
	 * 
	 * @param ctime
	 *            the value for interact_baoliao_object.ctime
	 * 
	 * @mbggenerated
	 */
	public void setCtime(Integer ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.uid
	 * 
	 * @return the value of interact_baoliao_object.uid
	 * 
	 * @mbggenerated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao_object.uid
	 * 
	 * @param uid
	 *            the value for interact_baoliao_object.uid
	 * 
	 * @mbggenerated
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	public int getIs_show() {
		return is_show;
	}

	public void setIs_show(int is_show) {
		this.is_show = is_show;
	}

	public String getJf_id() {
		return jf_id;
	}

	public void setJf_id(String jf_id) {
		this.jf_id = jf_id;
	}

	public String getB_desc() {
		return b_desc;
	}

	public void setB_desc(String b_desc) {
		this.b_desc = b_desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.jf_id
	 * 
	 * @return the value of interact_baoliao_object.jf_id
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao_object.b_desc
	 * 
	 * @return the value of interact_baoliao_object.b_desc
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */

}