package com.ctvit.bean;

import java.util.Date;

public class Interact_baoliao {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.id
	 * 
	 * @mbggenerated
	 */
	private int currentPage;
	private int pageSize;

	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.title
	 * 
	 * @mbggenerated
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.img_url
	 * 
	 * @mbggenerated
	 */
	private String img_url;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.vid_url
	 * 
	 * @mbggenerated
	 */
	private String vid_url;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.userid
	 * 
	 * @mbggenerated
	 */
	private String userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.username
	 * 
	 * @mbggenerated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.ip
	 * 
	 * @mbggenerated
	 */
	private String ip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.ctime
	 * 
	 * @mbggenerated
	 */
	private Date ctime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.check_time
	 * 
	 * @mbggenerated
	 */
	private Date check_time;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.status
	 * 
	 * @mbggenerated
	 */
	private Boolean status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.channelid
	 * 
	 * @mbggenerated
	 */
	private String channelid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.topicid
	 * 
	 * @mbggenerated
	 */
	private Boolean topicid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.parentid
	 * 
	 * @mbggenerated
	 */
	private Integer parentid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_baoliao.content
	 * 
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.id
	 * 
	 * @return the value of interact_baoliao.id
	 * 
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.id
	 * 
	 * @param id
	 *            the value for interact_baoliao.id
	 * 
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.title
	 * 
	 * @return the value of interact_baoliao.title
	 * 
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.title
	 * 
	 * @param title
	 *            the value for interact_baoliao.title
	 * 
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.img_url
	 * 
	 * @return the value of interact_baoliao.img_url
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.vid_url
	 * 
	 * @return the value of interact_baoliao.vid_url
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.userid
	 * 
	 * @return the value of interact_baoliao.userid
	 * 
	 * @mbggenerated
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.userid
	 * 
	 * @param userid
	 *            the value for interact_baoliao.userid
	 * 
	 * @mbggenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.username
	 * 
	 * @return the value of interact_baoliao.username
	 * 
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.username
	 * 
	 * @param username
	 *            the value for interact_baoliao.username
	 * 
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.ip
	 * 
	 * @return the value of interact_baoliao.ip
	 * 
	 * @mbggenerated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.ip
	 * 
	 * @param ip
	 *            the value for interact_baoliao.ip
	 * 
	 * @mbggenerated
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.ctime
	 * 
	 * @return the value of interact_baoliao.ctime
	 * 
	 * @mbggenerated
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.ctime
	 * 
	 * @param ctime
	 *            the value for interact_baoliao.ctime
	 * 
	 * @mbggenerated
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.check_time
	 * 
	 * @return the value of interact_baoliao.check_time
	 * 
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.status
	 * 
	 * @return the value of interact_baoliao.status
	 * 
	 * @mbggenerated
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.status
	 * 
	 * @param status
	 *            the value for interact_baoliao.status
	 * 
	 * @mbggenerated
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.channelid
	 * 
	 * @return the value of interact_baoliao.channelid
	 * 
	 * @mbggenerated
	 */
	public String getChannelid() {
		return channelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.channelid
	 * 
	 * @param channelid
	 *            the value for interact_baoliao.channelid
	 * 
	 * @mbggenerated
	 */
	public void setChannelid(String channelid) {
		this.channelid = channelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.topicid
	 * 
	 * @return the value of interact_baoliao.topicid
	 * 
	 * @mbggenerated
	 */
	public Boolean getTopicid() {
		return topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.topicid
	 * 
	 * @param topicid
	 *            the value for interact_baoliao.topicid
	 * 
	 * @mbggenerated
	 */
	public void setTopicid(Boolean topicid) {
		this.topicid = topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.parentid
	 * 
	 * @return the value of interact_baoliao.parentid
	 * 
	 * @mbggenerated
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.parentid
	 * 
	 * @param parentid
	 *            the value for interact_baoliao.parentid
	 * 
	 * @mbggenerated
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_baoliao.content
	 * 
	 * @return the value of interact_baoliao.content
	 * 
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_baoliao.content
	 * 
	 * @param content
	 *            the value for interact_baoliao.content
	 * 
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content;
	}

	public String getImg_url() {
		return img_url;
	}

	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}

	public String getVid_url() {
		return vid_url;
	}

	public void setVid_url(String vid_url) {
		this.vid_url = vid_url;
	}

	public Date getCheck_time() {
		return check_time;
	}

	public void setCheck_time(Date check_time) {
		this.check_time = check_time;
	}

	public int getCurrentPage() {
		return currentPage;
	}

	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */

}