package com.ctvit.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Interact_commentExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public Interact_commentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCommentidIsNull() {
			addCriterion("commentid is null");
			return (Criteria) this;
		}

		public Criteria andCommentidIsNotNull() {
			addCriterion("commentid is not null");
			return (Criteria) this;
		}

		public Criteria andCommentidEqualTo(Integer value) {
			addCriterion("commentid =", value, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidNotEqualTo(Integer value) {
			addCriterion("commentid <>", value, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidGreaterThan(Integer value) {
			addCriterion("commentid >", value, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidGreaterThanOrEqualTo(Integer value) {
			addCriterion("commentid >=", value, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidLessThan(Integer value) {
			addCriterion("commentid <", value, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidLessThanOrEqualTo(Integer value) {
			addCriterion("commentid <=", value, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidIn(List<Integer> values) {
			addCriterion("commentid in", values, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidNotIn(List<Integer> values) {
			addCriterion("commentid not in", values, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidBetween(Integer value1, Integer value2) {
			addCriterion("commentid between", value1, value2, "commentid");
			return (Criteria) this;
		}

		public Criteria andCommentidNotBetween(Integer value1, Integer value2) {
			addCriterion("commentid not between", value1, value2, "commentid");
			return (Criteria) this;
		}

		public Criteria andParentidIsNull() {
			addCriterion("parentid is null");
			return (Criteria) this;
		}

		public Criteria andParentidIsNotNull() {
			addCriterion("parentid is not null");
			return (Criteria) this;
		}

		public Criteria andParentidEqualTo(String value) {
			addCriterion("parentid =", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidNotEqualTo(String value) {
			addCriterion("parentid <>", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidGreaterThan(String value) {
			addCriterion("parentid >", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidGreaterThanOrEqualTo(String value) {
			addCriterion("parentid >=", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidLessThan(String value) {
			addCriterion("parentid <", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidLessThanOrEqualTo(String value) {
			addCriterion("parentid <=", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidLike(String value) {
			addCriterion("parentid like", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidNotLike(String value) {
			addCriterion("parentid not like", value, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidIn(List<String> values) {
			addCriterion("parentid in", values, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidNotIn(List<String> values) {
			addCriterion("parentid not in", values, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidBetween(String value1, String value2) {
			addCriterion("parentid between", value1, value2, "parentid");
			return (Criteria) this;
		}

		public Criteria andParentidNotBetween(String value1, String value2) {
			addCriterion("parentid not between", value1, value2, "parentid");
			return (Criteria) this;
		}

		public Criteria andItemidIsNull() {
			addCriterion("itemid is null");
			return (Criteria) this;
		}

		public Criteria andItemidIsNotNull() {
			addCriterion("itemid is not null");
			return (Criteria) this;
		}

		public Criteria andItemidEqualTo(String value) {
			addCriterion("itemid =", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotEqualTo(String value) {
			addCriterion("itemid <>", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThan(String value) {
			addCriterion("itemid >", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidGreaterThanOrEqualTo(String value) {
			addCriterion("itemid >=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThan(String value) {
			addCriterion("itemid <", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLessThanOrEqualTo(String value) {
			addCriterion("itemid <=", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidLike(String value) {
			addCriterion("itemid like", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotLike(String value) {
			addCriterion("itemid not like", value, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidIn(List<String> values) {
			addCriterion("itemid in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotIn(List<String> values) {
			addCriterion("itemid not in", values, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidBetween(String value1, String value2) {
			addCriterion("itemid between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemidNotBetween(String value1, String value2) {
			addCriterion("itemid not between", value1, value2, "itemid");
			return (Criteria) this;
		}

		public Criteria andItemtypeIsNull() {
			addCriterion("itemtype is null");
			return (Criteria) this;
		}

		public Criteria andItemtypeIsNotNull() {
			addCriterion("itemtype is not null");
			return (Criteria) this;
		}

		public Criteria andItemtypeEqualTo(String value) {
			addCriterion("itemtype =", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeNotEqualTo(String value) {
			addCriterion("itemtype <>", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeGreaterThan(String value) {
			addCriterion("itemtype >", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeGreaterThanOrEqualTo(String value) {
			addCriterion("itemtype >=", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeLessThan(String value) {
			addCriterion("itemtype <", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeLessThanOrEqualTo(String value) {
			addCriterion("itemtype <=", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeLike(String value) {
			addCriterion("itemtype like", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeNotLike(String value) {
			addCriterion("itemtype not like", value, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeIn(List<String> values) {
			addCriterion("itemtype in", values, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeNotIn(List<String> values) {
			addCriterion("itemtype not in", values, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeBetween(String value1, String value2) {
			addCriterion("itemtype between", value1, value2, "itemtype");
			return (Criteria) this;
		}

		public Criteria andItemtypeNotBetween(String value1, String value2) {
			addCriterion("itemtype not between", value1, value2, "itemtype");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("comment is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("comment is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("comment =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("comment <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("comment >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("comment >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("comment <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("comment <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("comment like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("comment not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("comment in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("comment not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("comment between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("comment not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userid like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userid not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUpcountIsNull() {
			addCriterion("upcount is null");
			return (Criteria) this;
		}

		public Criteria andUpcountIsNotNull() {
			addCriterion("upcount is not null");
			return (Criteria) this;
		}

		public Criteria andUpcountEqualTo(Integer value) {
			addCriterion("upcount =", value, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountNotEqualTo(Integer value) {
			addCriterion("upcount <>", value, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountGreaterThan(Integer value) {
			addCriterion("upcount >", value, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("upcount >=", value, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountLessThan(Integer value) {
			addCriterion("upcount <", value, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountLessThanOrEqualTo(Integer value) {
			addCriterion("upcount <=", value, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountIn(List<Integer> values) {
			addCriterion("upcount in", values, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountNotIn(List<Integer> values) {
			addCriterion("upcount not in", values, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountBetween(Integer value1, Integer value2) {
			addCriterion("upcount between", value1, value2, "upcount");
			return (Criteria) this;
		}

		public Criteria andUpcountNotBetween(Integer value1, Integer value2) {
			addCriterion("upcount not between", value1, value2, "upcount");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNull() {
			addCriterion("created is null");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNotNull() {
			addCriterion("created is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedEqualTo(Date value) {
			addCriterion("created =", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotEqualTo(Date value) {
			addCriterion("created <>", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThan(Date value) {
			addCriterion("created >", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("created >=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThan(Date value) {
			addCriterion("created <", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThanOrEqualTo(Date value) {
			addCriterion("created <=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedIn(List<Date> values) {
			addCriterion("created in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotIn(List<Date> values) {
			addCriterion("created not in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedBetween(Date value1, Date value2) {
			addCriterion("created between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotBetween(Date value1, Date value2) {
			addCriterion("created not between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Boolean value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Boolean value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Boolean value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Boolean value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Boolean value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Boolean> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Boolean> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Boolean value1, Boolean value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andDwcountIsNull() {
			addCriterion("dwcount is null");
			return (Criteria) this;
		}

		public Criteria andDwcountIsNotNull() {
			addCriterion("dwcount is not null");
			return (Criteria) this;
		}

		public Criteria andDwcountEqualTo(Integer value) {
			addCriterion("dwcount =", value, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountNotEqualTo(Integer value) {
			addCriterion("dwcount <>", value, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountGreaterThan(Integer value) {
			addCriterion("dwcount >", value, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("dwcount >=", value, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountLessThan(Integer value) {
			addCriterion("dwcount <", value, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountLessThanOrEqualTo(Integer value) {
			addCriterion("dwcount <=", value, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountIn(List<Integer> values) {
			addCriterion("dwcount in", values, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountNotIn(List<Integer> values) {
			addCriterion("dwcount not in", values, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountBetween(Integer value1, Integer value2) {
			addCriterion("dwcount between", value1, value2, "dwcount");
			return (Criteria) this;
		}

		public Criteria andDwcountNotBetween(Integer value1, Integer value2) {
			addCriterion("dwcount not between", value1, value2, "dwcount");
			return (Criteria) this;
		}

		public Criteria andChannelidIsNull() {
			addCriterion("channelid is null");
			return (Criteria) this;
		}

		public Criteria andChannelidIsNotNull() {
			addCriterion("channelid is not null");
			return (Criteria) this;
		}

		public Criteria andChannelidEqualTo(String value) {
			addCriterion("channelid =", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidNotEqualTo(String value) {
			addCriterion("channelid <>", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidGreaterThan(String value) {
			addCriterion("channelid >", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidGreaterThanOrEqualTo(String value) {
			addCriterion("channelid >=", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidLessThan(String value) {
			addCriterion("channelid <", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidLessThanOrEqualTo(String value) {
			addCriterion("channelid <=", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidLike(String value) {
			addCriterion("channelid like", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidNotLike(String value) {
			addCriterion("channelid not like", value, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidIn(List<String> values) {
			addCriterion("channelid in", values, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidNotIn(List<String> values) {
			addCriterion("channelid not in", values, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidBetween(String value1, String value2) {
			addCriterion("channelid between", value1, value2, "channelid");
			return (Criteria) this;
		}

		public Criteria andChannelidNotBetween(String value1, String value2) {
			addCriterion("channelid not between", value1, value2, "channelid");
			return (Criteria) this;
		}

		public Criteria andTopicidIsNull() {
			addCriterion("topicid is null");
			return (Criteria) this;
		}

		public Criteria andTopicidIsNotNull() {
			addCriterion("topicid is not null");
			return (Criteria) this;
		}

		public Criteria andTopicidEqualTo(String value) {
			addCriterion("topicid =", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidNotEqualTo(String value) {
			addCriterion("topicid <>", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidGreaterThan(String value) {
			addCriterion("topicid >", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidGreaterThanOrEqualTo(String value) {
			addCriterion("topicid >=", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidLessThan(String value) {
			addCriterion("topicid <", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidLessThanOrEqualTo(String value) {
			addCriterion("topicid <=", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidLike(String value) {
			addCriterion("topicid like", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidNotLike(String value) {
			addCriterion("topicid not like", value, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidIn(List<String> values) {
			addCriterion("topicid in", values, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidNotIn(List<String> values) {
			addCriterion("topicid not in", values, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidBetween(String value1, String value2) {
			addCriterion("topicid between", value1, value2, "topicid");
			return (Criteria) this;
		}

		public Criteria andTopicidNotBetween(String value1, String value2) {
			addCriterion("topicid not between", value1, value2, "topicid");
			return (Criteria) this;
		}

		public Criteria andUserheadIsNull() {
			addCriterion("userhead is null");
			return (Criteria) this;
		}

		public Criteria andUserheadIsNotNull() {
			addCriterion("userhead is not null");
			return (Criteria) this;
		}

		public Criteria andUserheadEqualTo(String value) {
			addCriterion("userhead =", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadNotEqualTo(String value) {
			addCriterion("userhead <>", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadGreaterThan(String value) {
			addCriterion("userhead >", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadGreaterThanOrEqualTo(String value) {
			addCriterion("userhead >=", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadLessThan(String value) {
			addCriterion("userhead <", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadLessThanOrEqualTo(String value) {
			addCriterion("userhead <=", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadLike(String value) {
			addCriterion("userhead like", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadNotLike(String value) {
			addCriterion("userhead not like", value, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadIn(List<String> values) {
			addCriterion("userhead in", values, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadNotIn(List<String> values) {
			addCriterion("userhead not in", values, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadBetween(String value1, String value2) {
			addCriterion("userhead between", value1, value2, "userhead");
			return (Criteria) this;
		}

		public Criteria andUserheadNotBetween(String value1, String value2) {
			addCriterion("userhead not between", value1, value2, "userhead");
			return (Criteria) this;
		}

		public Criteria andReplycommentidIsNull() {
			addCriterion("replycommentid is null");
			return (Criteria) this;
		}

		public Criteria andReplycommentidIsNotNull() {
			addCriterion("replycommentid is not null");
			return (Criteria) this;
		}

		public Criteria andReplycommentidEqualTo(Integer value) {
			addCriterion("replycommentid =", value, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidNotEqualTo(Integer value) {
			addCriterion("replycommentid <>", value, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidGreaterThan(Integer value) {
			addCriterion("replycommentid >", value, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidGreaterThanOrEqualTo(Integer value) {
			addCriterion("replycommentid >=", value, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidLessThan(Integer value) {
			addCriterion("replycommentid <", value, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidLessThanOrEqualTo(Integer value) {
			addCriterion("replycommentid <=", value, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidIn(List<Integer> values) {
			addCriterion("replycommentid in", values, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidNotIn(List<Integer> values) {
			addCriterion("replycommentid not in", values, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidBetween(Integer value1, Integer value2) {
			addCriterion("replycommentid between", value1, value2, "replycommentid");
			return (Criteria) this;
		}

		public Criteria andReplycommentidNotBetween(Integer value1, Integer value2) {
			addCriterion("replycommentid not between", value1, value2, "replycommentid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table interact_comment
	 * 
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}