package com.ctvit.bean;

import java.util.Date;

public class Interact_comment {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.commentid
	 * 
	 * @mbggenerated
	 */
	private int currentPage;
	private int pageSize;
	private String start;
	private String end;
	private Integer commentid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.parentid
	 * 
	 * @mbggenerated
	 */
	private String parentid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.itemid
	 * 
	 * @mbggenerated
	 */
	private String itemid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.itemtype
	 * 
	 * @mbggenerated
	 */
	private String itemtype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.comment
	 * 
	 * @mbggenerated
	 */
	private String comment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.ip
	 * 
	 * @mbggenerated
	 */
	private String ip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.userid
	 * 
	 * @mbggenerated
	 */
	private String userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.username
	 * 
	 * @mbggenerated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.upcount
	 * 
	 * @mbggenerated
	 */
	private Integer upcount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.created
	 * 
	 * @mbggenerated
	 */
	private Date created;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.status
	 * 
	 * @mbggenerated
	 */
	private Boolean status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.dwcount
	 * 
	 * @mbggenerated
	 */
	private Integer dwcount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.channelid
	 * 
	 * @mbggenerated
	 */
	private String channelid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.topicid
	 * 
	 * @mbggenerated
	 */
	private String topicid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.userhead
	 * 
	 * @mbggenerated
	 */
	private String userhead;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interact_comment.replycommentid
	 * 
	 * @mbggenerated
	 */
	private Integer replycommentid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.commentid
	 * 
	 * @return the value of interact_comment.commentid
	 * 
	 * @mbggenerated
	 */
	public Integer getCommentid() {
		return commentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.commentid
	 * 
	 * @param commentid
	 *            the value for interact_comment.commentid
	 * 
	 * @mbggenerated
	 */

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	public int getCurrentPage() {
		return currentPage;
	}

	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.parentid
	 * 
	 * @return the value of interact_comment.parentid
	 * 
	 * @mbggenerated
	 */
	public String getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.parentid
	 * 
	 * @param parentid
	 *            the value for interact_comment.parentid
	 * 
	 * @mbggenerated
	 */
	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.itemid
	 * 
	 * @return the value of interact_comment.itemid
	 * 
	 * @mbggenerated
	 */
	public String getItemid() {
		return itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.itemid
	 * 
	 * @param itemid
	 *            the value for interact_comment.itemid
	 * 
	 * @mbggenerated
	 */
	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.itemtype
	 * 
	 * @return the value of interact_comment.itemtype
	 * 
	 * @mbggenerated
	 */
	public String getItemtype() {
		return itemtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.itemtype
	 * 
	 * @param itemtype
	 *            the value for interact_comment.itemtype
	 * 
	 * @mbggenerated
	 */
	public void setItemtype(String itemtype) {
		this.itemtype = itemtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.comment
	 * 
	 * @return the value of interact_comment.comment
	 * 
	 * @mbggenerated
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.comment
	 * 
	 * @param comment
	 *            the value for interact_comment.comment
	 * 
	 * @mbggenerated
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.ip
	 * 
	 * @return the value of interact_comment.ip
	 * 
	 * @mbggenerated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.ip
	 * 
	 * @param ip
	 *            the value for interact_comment.ip
	 * 
	 * @mbggenerated
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.userid
	 * 
	 * @return the value of interact_comment.userid
	 * 
	 * @mbggenerated
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.userid
	 * 
	 * @param userid
	 *            the value for interact_comment.userid
	 * 
	 * @mbggenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.username
	 * 
	 * @return the value of interact_comment.username
	 * 
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.username
	 * 
	 * @param username
	 *            the value for interact_comment.username
	 * 
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.upcount
	 * 
	 * @return the value of interact_comment.upcount
	 * 
	 * @mbggenerated
	 */
	public Integer getUpcount() {
		return upcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.upcount
	 * 
	 * @param upcount
	 *            the value for interact_comment.upcount
	 * 
	 * @mbggenerated
	 */
	public void setUpcount(Integer upcount) {
		this.upcount = upcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.created
	 * 
	 * @return the value of interact_comment.created
	 * 
	 * @mbggenerated
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.created
	 * 
	 * @param created
	 *            the value for interact_comment.created
	 * 
	 * @mbggenerated
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.status
	 * 
	 * @return the value of interact_comment.status
	 * 
	 * @mbggenerated
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.status
	 * 
	 * @param status
	 *            the value for interact_comment.status
	 * 
	 * @mbggenerated
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.dwcount
	 * 
	 * @return the value of interact_comment.dwcount
	 * 
	 * @mbggenerated
	 */
	public Integer getDwcount() {
		return dwcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.dwcount
	 * 
	 * @param dwcount
	 *            the value for interact_comment.dwcount
	 * 
	 * @mbggenerated
	 */

	public void setDwcount(Integer dwcount) {
		this.dwcount = dwcount;
	}

	public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.channelid
	 * 
	 * @return the value of interact_comment.channelid
	 * 
	 * @mbggenerated
	 */
	public String getChannelid() {
		return channelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.channelid
	 * 
	 * @param channelid
	 *            the value for interact_comment.channelid
	 * 
	 * @mbggenerated
	 */
	public void setChannelid(String channelid) {
		this.channelid = channelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.topicid
	 * 
	 * @return the value of interact_comment.topicid
	 * 
	 * @mbggenerated
	 */
	public String getTopicid() {
		return topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.topicid
	 * 
	 * @param topicid
	 *            the value for interact_comment.topicid
	 * 
	 * @mbggenerated
	 */
	public void setTopicid(String topicid) {
		this.topicid = topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.userhead
	 * 
	 * @return the value of interact_comment.userhead
	 * 
	 * @mbggenerated
	 */
	public String getUserhead() {
		return userhead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.userhead
	 * 
	 * @param userhead
	 *            the value for interact_comment.userhead
	 * 
	 * @mbggenerated
	 */
	public void setUserhead(String userhead) {
		this.userhead = userhead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interact_comment.replycommentid
	 * 
	 * @return the value of interact_comment.replycommentid
	 * 
	 * @mbggenerated
	 */
	public Integer getReplycommentid() {
		return replycommentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interact_comment.replycommentid
	 * 
	 * @param replycommentid
	 *            the value for interact_comment.replycommentid
	 * 
	 * @mbggenerated
	 */
	public void setReplycommentid(Integer replycommentid) {
		this.replycommentid = replycommentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Interact_comment other = (Interact_comment) that;
		return (this.getCommentid() == null ? other.getCommentid() == null : this.getCommentid().equals(other.getCommentid())) && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid())) && (this.getItemid() == null ? other.getItemid() == null : this.getItemid().equals(other.getItemid())) && (this.getItemtype() == null ? other.getItemtype() == null : this.getItemtype().equals(other.getItemtype()))
				&& (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment())) && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp())) && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid())) && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
				&& (this.getUpcount() == null ? other.getUpcount() == null : this.getUpcount().equals(other.getUpcount())) && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated())) && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus())) && (this.getDwcount() == null ? other.getDwcount() == null : this.getDwcount().equals(other.getDwcount()))
				&& (this.getChannelid() == null ? other.getChannelid() == null : this.getChannelid().equals(other.getChannelid())) && (this.getTopicid() == null ? other.getTopicid() == null : this.getTopicid().equals(other.getTopicid())) && (this.getUserhead() == null ? other.getUserhead() == null : this.getUserhead().equals(other.getUserhead())) && (this.getReplycommentid() == null ? other.getReplycommentid() == null : this.getReplycommentid().equals(other.getReplycommentid()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getCommentid() == null) ? 0 : getCommentid().hashCode());
		result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
		result = prime * result + ((getItemid() == null) ? 0 : getItemid().hashCode());
		result = prime * result + ((getItemtype() == null) ? 0 : getItemtype().hashCode());
		result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
		result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
		result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
		result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
		result = prime * result + ((getUpcount() == null) ? 0 : getUpcount().hashCode());
		result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getDwcount() == null) ? 0 : getDwcount().hashCode());
		result = prime * result + ((getChannelid() == null) ? 0 : getChannelid().hashCode());
		result = prime * result + ((getTopicid() == null) ? 0 : getTopicid().hashCode());
		result = prime * result + ((getUserhead() == null) ? 0 : getUserhead().hashCode());
		result = prime * result + ((getReplycommentid() == null) ? 0 : getReplycommentid().hashCode());
		return result;
	}
}