package com.ctvit.bean;

public class Tab_programme_save {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.orderId
	 *
	 * @mbggenerated
	 */
	private Integer orderid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.programme_save_id
	 *
	 * @mbggenerated
	 */
	private String programme_save_id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.waccountId
	 *
	 * @mbggenerated
	 */
	private String waccountid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.openId
	 *
	 * @mbggenerated
	 */
	private String openid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.image
	 *
	 * @mbggenerated
	 */
	private String image;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.insertTime
	 *
	 * @mbggenerated
	 */
	private String inserttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.updateTime
	 *
	 * @mbggenerated
	 */
	private String updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.flag
	 *
	 * @mbggenerated
	 */
	private Integer flag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.huifu
	 *
	 * @mbggenerated
	 */
	private String huifu;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.video
	 *
	 * @mbggenerated
	 */
	private String video;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.audio
	 *
	 * @mbggenerated
	 */
	private String audio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.type
	 *
	 * @mbggenerated
	 */
	private Integer type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.xuanzhuan
	 *
	 * @mbggenerated
	 */
	private Integer xuanzhuan;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.sex
	 *
	 * @mbggenerated
	 */
	private String sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.city
	 *
	 * @mbggenerated
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.country
	 *
	 * @mbggenerated
	 */
	private String country;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.province
	 *
	 * @mbggenerated
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.headimgurl
	 *
	 * @mbggenerated
	 */
	private String headimgurl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tab_programme_save.pid
	 *
	 * @mbggenerated
	 */
	private Integer pid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.id
	 *
	 * @return the value of tab_programme_save.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.id
	 *
	 * @param id
	 *            the value for tab_programme_save.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.orderId
	 *
	 * @return the value of tab_programme_save.orderId
	 *
	 * @mbggenerated
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.orderId
	 *
	 * @param orderid
	 *            the value for tab_programme_save.orderId
	 *
	 * @mbggenerated
	 */

	public String getProgramme_save_id() {
		return programme_save_id;
	}

	public void setProgramme_save_id(String programme_save_id) {
		this.programme_save_id = programme_save_id;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.programme_save_id
	 *
	 * @return the value of tab_programme_save.programme_save_id
	 *
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.programme_save_id
	 *
	 * @param programmeSaveId
	 *            the value for tab_programme_save.programme_save_id
	 *
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.waccountId
	 *
	 * @return the value of tab_programme_save.waccountId
	 *
	 * @mbggenerated
	 */
	public String getWaccountid() {
		return waccountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.waccountId
	 *
	 * @param waccountid
	 *            the value for tab_programme_save.waccountId
	 *
	 * @mbggenerated
	 */
	public void setWaccountid(String waccountid) {
		this.waccountid = waccountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.openId
	 *
	 * @return the value of tab_programme_save.openId
	 *
	 * @mbggenerated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.openId
	 *
	 * @param openid
	 *            the value for tab_programme_save.openId
	 *
	 * @mbggenerated
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.image
	 *
	 * @return the value of tab_programme_save.image
	 *
	 * @mbggenerated
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.image
	 *
	 * @param image
	 *            the value for tab_programme_save.image
	 *
	 * @mbggenerated
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.insertTime
	 *
	 * @return the value of tab_programme_save.insertTime
	 *
	 * @mbggenerated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.insertTime
	 *
	 * @param inserttime
	 *            the value for tab_programme_save.insertTime
	 *
	 * @mbggenerated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.updateTime
	 *
	 * @return the value of tab_programme_save.updateTime
	 *
	 * @mbggenerated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.updateTime
	 *
	 * @param updatetime
	 *            the value for tab_programme_save.updateTime
	 *
	 * @mbggenerated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.flag
	 *
	 * @return the value of tab_programme_save.flag
	 *
	 * @mbggenerated
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.flag
	 *
	 * @param flag
	 *            the value for tab_programme_save.flag
	 *
	 * @mbggenerated
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.huifu
	 *
	 * @return the value of tab_programme_save.huifu
	 *
	 * @mbggenerated
	 */
	public String getHuifu() {
		return huifu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.huifu
	 *
	 * @param huifu
	 *            the value for tab_programme_save.huifu
	 *
	 * @mbggenerated
	 */
	public void setHuifu(String huifu) {
		this.huifu = huifu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.video
	 *
	 * @return the value of tab_programme_save.video
	 *
	 * @mbggenerated
	 */
	public String getVideo() {
		return video;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.video
	 *
	 * @param video
	 *            the value for tab_programme_save.video
	 *
	 * @mbggenerated
	 */
	public void setVideo(String video) {
		this.video = video;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.audio
	 *
	 * @return the value of tab_programme_save.audio
	 *
	 * @mbggenerated
	 */
	public String getAudio() {
		return audio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.audio
	 *
	 * @param audio
	 *            the value for tab_programme_save.audio
	 *
	 * @mbggenerated
	 */
	public void setAudio(String audio) {
		this.audio = audio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.type
	 *
	 * @return the value of tab_programme_save.type
	 *
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.type
	 *
	 * @param type
	 *            the value for tab_programme_save.type
	 *
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.xuanzhuan
	 *
	 * @return the value of tab_programme_save.xuanzhuan
	 *
	 * @mbggenerated
	 */
	public Integer getXuanzhuan() {
		return xuanzhuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.xuanzhuan
	 *
	 * @param xuanzhuan
	 *            the value for tab_programme_save.xuanzhuan
	 *
	 * @mbggenerated
	 */
	public void setXuanzhuan(Integer xuanzhuan) {
		this.xuanzhuan = xuanzhuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.sex
	 *
	 * @return the value of tab_programme_save.sex
	 *
	 * @mbggenerated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.sex
	 *
	 * @param sex
	 *            the value for tab_programme_save.sex
	 *
	 * @mbggenerated
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.city
	 *
	 * @return the value of tab_programme_save.city
	 *
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.city
	 *
	 * @param city
	 *            the value for tab_programme_save.city
	 *
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.country
	 *
	 * @return the value of tab_programme_save.country
	 *
	 * @mbggenerated
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.country
	 *
	 * @param country
	 *            the value for tab_programme_save.country
	 *
	 * @mbggenerated
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.province
	 *
	 * @return the value of tab_programme_save.province
	 *
	 * @mbggenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.province
	 *
	 * @param province
	 *            the value for tab_programme_save.province
	 *
	 * @mbggenerated
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.headimgurl
	 *
	 * @return the value of tab_programme_save.headimgurl
	 *
	 * @mbggenerated
	 */
	public String getHeadimgurl() {
		return headimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.headimgurl
	 *
	 * @param headimgurl
	 *            the value for tab_programme_save.headimgurl
	 *
	 * @mbggenerated
	 */
	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tab_programme_save.pid
	 *
	 * @return the value of tab_programme_save.pid
	 *
	 * @mbggenerated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tab_programme_save.pid
	 *
	 * @param pid
	 *            the value for tab_programme_save.pid
	 *
	 * @mbggenerated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tab_programme_save
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Tab_programme_save other = (Tab_programme_save) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid())) && (this.getProgramme_save_id() == null ? other.getProgramme_save_id() == null : this.getProgramme_save_id().equals(other.getProgramme_save_id())) && (this.getWaccountid() == null ? other.getWaccountid() == null : this.getWaccountid().equals(other.getWaccountid()))
				&& (this.getOpenid() == null ? other.getOpenid() == null : this.getOpenid().equals(other.getOpenid())) && (this.getImage() == null ? other.getImage() == null : this.getImage().equals(other.getImage())) && (this.getInserttime() == null ? other.getInserttime() == null : this.getInserttime().equals(other.getInserttime())) && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
				&& (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag())) && (this.getHuifu() == null ? other.getHuifu() == null : this.getHuifu().equals(other.getHuifu())) && (this.getVideo() == null ? other.getVideo() == null : this.getVideo().equals(other.getVideo())) && (this.getAudio() == null ? other.getAudio() == null : this.getAudio().equals(other.getAudio()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType())) && (this.getXuanzhuan() == null ? other.getXuanzhuan() == null : this.getXuanzhuan().equals(other.getXuanzhuan())) && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex())) && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
				&& (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry())) && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince())) && (this.getHeadimgurl() == null ? other.getHeadimgurl() == null : this.getHeadimgurl().equals(other.getHeadimgurl())) && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tab_programme_save
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
		result = prime * result + ((getProgramme_save_id() == null) ? 0 : getProgramme_save_id().hashCode());
		result = prime * result + ((getWaccountid() == null) ? 0 : getWaccountid().hashCode());
		result = prime * result + ((getOpenid() == null) ? 0 : getOpenid().hashCode());
		result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
		result = prime * result + ((getInserttime() == null) ? 0 : getInserttime().hashCode());
		result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
		result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
		result = prime * result + ((getHuifu() == null) ? 0 : getHuifu().hashCode());
		result = prime * result + ((getVideo() == null) ? 0 : getVideo().hashCode());
		result = prime * result + ((getAudio() == null) ? 0 : getAudio().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result + ((getXuanzhuan() == null) ? 0 : getXuanzhuan().hashCode());
		result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
		result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
		result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
		result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
		result = prime * result + ((getHeadimgurl() == null) ? 0 : getHeadimgurl().hashCode());
		result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
		return result;
	}
}