package com.ctvit.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ctvit.bean.Interact_comment;
import com.ctvit.bean.Interact_commentExample;

public interface Interact_commentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int countByExample(Interact_commentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(Interact_commentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer commentid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int insert(Interact_comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Interact_comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	List<Interact_comment> selectByExample(Interact_commentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	Interact_comment selectByPrimaryKey(Integer commentid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Interact_comment record, @Param("example") Interact_commentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Interact_comment record, @Param("example") Interact_commentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Interact_comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_comment
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Interact_comment record);

	List<Interact_comment> selectcomment(Interact_comment comment);

	List<Interact_comment> searchcomment(Interact_comment comment);
}