package com.ctvit.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ctvit.bean.Interact_baoliao_object;
import com.ctvit.bean.Interact_baoliao_objectExample;

public interface Interact_baoliao_objectMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int countByExample(Interact_baoliao_objectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(Interact_baoliao_objectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int insert(Interact_baoliao_object record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Interact_baoliao_object record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	List<Interact_baoliao_object> selectByExampleWithBLOBs(Interact_baoliao_objectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	List<Interact_baoliao_object> selectByExample(Interact_baoliao_objectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	Interact_baoliao_object selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Interact_baoliao_object record, @Param("example") Interact_baoliao_objectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") Interact_baoliao_object record, @Param("example") Interact_baoliao_objectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Interact_baoliao_object record, @Param("example") Interact_baoliao_objectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Interact_baoliao_object record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Interact_baoliao_object record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao_object
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Interact_baoliao_object record);

	Interact_baoliao_object getinfo(Interact_baoliao_object baoliaoObject);
}