package com.ctvit.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ctvit.bean.Interact_baoliao;
import com.ctvit.bean.Interact_baoliaoExample;
import com.ctvit.bean.Interact_baoliaoExt;

public interface Interact_baoliaoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int countByExample(Interact_baoliaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(Interact_baoliaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int insert(Interact_baoliao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Interact_baoliao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	List<Interact_baoliao> selectByExampleWithBLOBs(Interact_baoliaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	List<Interact_baoliao> selectByExample(Interact_baoliaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	Interact_baoliao selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Interact_baoliao record, @Param("example") Interact_baoliaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") Interact_baoliao record, @Param("example") Interact_baoliaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Interact_baoliao record, @Param("example") Interact_baoliaoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Interact_baoliao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Interact_baoliao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interact_baoliao
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Interact_baoliao record);

	List<Interact_baoliaoExt> select(Interact_baoliao baoliao);

	Interact_baoliaoExt getUser(Interact_baoliaoExt interact_baoliaoExt);

	List<Interact_baoliaoExt> search(Interact_baoliao baoliao);
}